// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse_Management_System.Data;

#nullable disable

namespace Warehouse_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240502205806_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse_Management_System.Models.DepartmentMaterialRequisition", b =>
                {
                    b.Property<int>("DMRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DMRId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedItem1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedItem2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedItem3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedItem4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedItem5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DMRId");

                    b.ToTable("DepartmentMaterialRequisitions");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.Dispatch", b =>
                {
                    b.Property<int>("DispatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispatchId"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityDispatched")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDispatched1")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDispatched2")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDispatched3")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderNumber")
                        .HasColumnType("int");

                    b.HasKey("DispatchId");

                    b.ToTable("Dispatchs");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.Inventory", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<string>("ContactDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<string>("Goods_service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_service1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_service2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_service3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_service4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_service5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseRequisitionId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Quantity1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity2")
                        .HasColumnType("int");

                    b.Property<int>("Quantity3")
                        .HasColumnType("int");

                    b.Property<int>("Quantity4")
                        .HasColumnType("int");

                    b.Property<int>("Quantity5")
                        .HasColumnType("int");

                    b.Property<string>("SupplierAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Vat")
                        .HasColumnType("real");

                    b.HasKey("PurchaseOrderId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.PurchaseRequisition", b =>
                {
                    b.Property<int>("RequisitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequisitionId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantity1")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantity2")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantity3")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantity4")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantity5")
                        .HasColumnType("int");

                    b.Property<string>("PurposeOfPurchase")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequisitionId");

                    b.ToTable("PurchaseRequisitions");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.SalesOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProduct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProduct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProduct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProduct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProduct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProduct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldProducts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.StoresGoodsReceivedVoucher", b =>
                {
                    b.Property<int>("GRVNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRVNumber"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryNoteNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<int>("OffloadingAuthorisationNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GRVNumber");

                    b.ToTable("StoresGoodsReceivedVouchers");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.StoresIssueSlip", b =>
                {
                    b.Property<int>("IssueNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueNumber"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IssueNumber");

                    b.ToTable("StoresIssueSlips");
                });

            modelBuilder.Entity("Warehouse_Management_System.Models.WarehouseStock", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("ClosingBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningBalance")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Production")
                        .HasColumnType("int");

                    b.Property<int>("Returns")
                        .HasColumnType("int");

                    b.Property<int>("SalesDispatch")
                        .HasColumnType("int");

                    b.Property<int>("Samples")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("WarehouseStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
