namespace Warehouse_Management_System.DataTransferObjects.PurchaseRequisitionDTOs
{
    public class UpdatePurchaseRequisionDTO
    { 
        public string? EmployeeName { get; set; }
        public string? Department { get; set; }
        public string?  PurposeOfPurchase { get; set; }
        public string? ProductName { get; set; }
        public int ProductQuantity { get; set; }
        public string? ProductName1 { get; set; }
        public int ProductQuantity1 { get; set; }
        public string? ProductName2 { get; set; }
        public int ProductQuantity2 { get; set; }
        public string? ProductName3 { get; set; }
        public int ProductQuantity3 { get; set; }
        public string? ProductName4 { get; set; }
        public int ProductQuantity4 { get; set; }
        public string? ProductName5 { get; set; }
        public int ProductQuantity5 { get; set; }
    }
}